// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360Pro.Infrastructure.Persistence.Contexts;

#nullable disable

namespace eVote360Pro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(eVote360ProDbContext))]
    partial class eVote360ProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Alliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Party1Id")
                        .HasColumnType("int");

                    b.Property<int>("Party2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Party1Id");

                    b.HasIndex("Party2Id");

                    b.ToTable("Alianzas", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.AllianceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantPartyId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantPartyId");

                    b.HasIndex("ReceiverPartyId");

                    b.ToTable("SolicitudesAlianzas", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ParticipatedInElection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Candidatos", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.CandidatePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectivePositionId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("CandidatePositions");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.CitizenVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int?>("CitizenId1")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int?>("ElectionId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId1");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectionId1");

                    b.HasIndex("CitizenId", "ElectionId")
                        .IsUnique();

                    b.ToTable("VotosCiudadanos", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.ElectivePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ElectivePositions", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PoliticalLeaderAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AsignacionesDirigentes", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PoliticalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartidosPoliticos", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.VerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int?>("CitizenId1")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int?>("ElectionId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CitizenId1");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectionId1");

                    b.HasIndex("CitizenId", "ElectionId");

                    b.ToTable("CodigosVerificacion", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectivePositionId");

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Alliance", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "Party1")
                        .WithMany("AlliancesAsParty1")
                        .HasForeignKey("Party1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "Party2")
                        .WithMany("AlliancesAsParty2")
                        .HasForeignKey("Party2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Party1");

                    b.Navigation("Party2");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.AllianceRequest", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "ApplicantParty")
                        .WithMany("SentAllianceRequests")
                        .HasForeignKey("ApplicantPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "ReceiverParty")
                        .WithMany("ReceivedAllianceRequests")
                        .HasForeignKey("ReceiverPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicantParty");

                    b.Navigation("ReceiverParty");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("Candidates")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.CandidatePosition", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany("CandidatePositions")
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("ElectivePosition");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.CitizenVote", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Citizen", null)
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Citizen", "Citizen")
                        .WithMany("CitizenVotes")
                        .HasForeignKey("CitizenId1");

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Election", null)
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Election", "Election")
                        .WithMany("CitizenVotes")
                        .HasForeignKey("ElectionId1");

                    b.Navigation("Citizen");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PoliticalLeaderAssignment", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithOne("PoliticalLeaderAssignment")
                        .HasForeignKey("eVote360Pro.Core.Domain.Entities.PoliticalLeaderAssignment", "PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoliticalParty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.VerificationCode", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Citizen", null)
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Citizen", "Citizen")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("CitizenId1");

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Election", null)
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId1");

                    b.Navigation("Citizen");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Vote", b =>
                {
                    b.HasOne("eVote360Pro.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eVote360Pro.Core.Domain.Entities.Election", "Election")
                        .WithMany("Votes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360Pro.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany("Votes")
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Election");

                    b.Navigation("ElectivePosition");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Citizen", b =>
                {
                    b.Navigation("CitizenVotes");

                    b.Navigation("VerificationCodes");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.Election", b =>
                {
                    b.Navigation("CitizenVotes");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.ElectivePosition", b =>
                {
                    b.Navigation("CandidatePositions");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote360Pro.Core.Domain.Entities.PoliticalParty", b =>
                {
                    b.Navigation("AlliancesAsParty1");

                    b.Navigation("AlliancesAsParty2");

                    b.Navigation("Candidates");

                    b.Navigation("PoliticalLeaderAssignment");

                    b.Navigation("ReceivedAllianceRequests");

                    b.Navigation("SentAllianceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
